services:
  - type: web
    name: machine-learning-lab
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 # Adjust if you have a specific version in mind
